version: '3.1'

services:
  # for testing publish packages
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - './.verdaccio:/verdaccio/conf'
